name: Java CI with Maven (Java 11, Spring Boot 2.6.6)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn clean install

      - name: Deploy to Render
        run: curl -X POST https://api.render.com/deploy/srv-d0d06e6mcj7s73b21h1g?key=AYkXFb_huRc